spring:
  profiles:
    active: dev
  application:
    name: db_promote_service
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML5

server:
  port: 16110
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat

logging:
  level:
    com.db.promote: INFO

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 短信相关配置
sms:
  #用户名
  userName: 15378711196
  #密码
  passWord: 711196
  #请求地址
  reqUrl: http://smsapi.jzyyun.com:9003/servlet/UserServiceAPI
  #签名
  sign: 【e销售】
