logging:
  level:
    com.db.promote: DEBUG

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: "jdbc:mysql://122.114.214.7:3306/db_data?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=true"
    username: root
    password: root
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

