server:
  port: 16110
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat



logging:
  level:
    com.db.promote: INFO

spring:
  application:
    name: db_promote_service
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML5

