server:
  port: 16110
logging:
  level:
    com.db.promote: INFO

spring:
  profiles: dev

db:
  #本模块数据库
  master:
    url: "jdbc:mysql://localhost:3306/db_data?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=true"
    username: root
    password: root
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 1
    maxActive: 2
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
